theme: jekyll-theme-cayman
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Application Setup
    url: setup
  - title: Process the Data
    url: process_data
  - title: Run the Application
    url: runningApplication
  - title: Extras
    url: extras
  # - title: Running Federated Training
  #   url: fl
  - title: (08/04/2025) Running Federated Training
    url: fl_april
  - title: ITCR Connectivity
    url: itcr_connectivity